### ISSUE TITLE
Button select for users

### ISSUE THREAD

**Issue by Stuartemk** [nikosdion/DarkMagic#3]
**Is your feature request related to a problem? Please describe.**

Hello, is there any possibility to add a button for the user to choose the theme.

Thanks

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Why do you think this is relevant to people other than you**
Describe use cases other than yours that you have considered when deciding that your requested feature will benefit the community, not just you or a few people with your narrow use case.

**Additional context**

**Comment by nikosdion** [comment]
If you want to create a custom CSS style for your site use the SCSS sources shipped with the plugin and [found in this repository](https://github.com/nikosdion/DarkMagic/tree/development/plugins/system/darkmagic/media/scss) to create your new CSS files atum.css (backend) and cassiopeia.css (frontend). To change the TinyMCE CSS file (skin.css) use the [skintool.json file in this repository](https://github.com/nikosdion/DarkMagic/tree/development/tinyMce_Skin) with the [TinyMCE Skin Tool](http://skin.tiny.cloud/t5/?_ga=2.235499649.1875473097.1648018933-1074212806.1648018933).

All of your generated CSS files MUST NOT replace the files in the plugin itself. Do them as media overrides in your template's css/plg_system_darkmagic directory — also read [how to do media overrides in Joomla's documentation](https://docs.joomla.org/Understanding_Output_Overrides#Media_Files_Override).

Since customisation is fully possible with core Joomla features which have existed for well over 12 years I don't see any reason to reinvent the wheel and make it square.

**Comment by woluweb** [comment]
Hi there,
It could be that there is a misunderstanding : 
- @Stuartemk was indeed maybe asking for the possibility to "choose a theme" in the sense of customizing the CSS (having another Theme), which is indeed not necessary as Joomla already provides all is needed
- but when reading his question again, I think he meant "is it possible to have a Switch in the front-end allowing the visitors to choose freely/manually between the Dark and Light Mode"

**Comment by Stuartemk** [comment]
That's right!

**Comment by nikosdion** [comment]
No, I am **NOT** doing that. It's fundamentally wrong.

Modern browsers communicate the user's Operating System-wide preference via [the CSS media feature `prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme). The last major browser to support this feature was released three years ago. At this point it is to be considered an accessibility preference communicated by the browser and respected as a result.

While there are two plugin options to always use the dark theme or follow the sun they are obsolete and will be removed in a future version.

Using a selector in the front-end is not just fundamentally wrong but also complicated programmatically. To begin with, a plugin cannot possibly render a control... You'd need a module. The whole site would appear with a light theme until JavaScript initialises which could be several seconds into the page load or never, if the user has turned JavaScript off or they are using a script blocker. Maintaining the user's preference requires a cookie which has to be disclosed and controlled by a cookie popup as it's not a mandatory selection. In fact, if the user chooses not to accept cookies this control needs to go away. The control needs to be tristate (off, auto, on) with the auto position respecting the browser's choice AND reacting to the global light/dark selection changing. This is non-trivial and can have some serious side-effects to your page.

In the end of the day it's a complicated and error-prone way to implement something which is fundamentally wrong. If the user wants to change between light and dark mode they can do it at the browser level or the OS level. They MUST NOT need a control _per site_ to apply an accessibility preference already communicated by the browser!

**Comment by woluweb** [comment]
Txs for taking the time to explain.
(so one could say that a "_Light_ switch" is a _Dark_ pattern :D )

**Comment by nikosdion** [comment]
> (so one could say that a "Light switch" is a Dark pattern :D )

![Ba-dum-tss](https://media.giphy.com/media/kPIswn0RfPTGxOvDj5/giphy-downsized.gif)
